import type { SeedContent } from "./dsa";

export const hldContent: SeedContent[] = [
  // Concepts
  { id: "hld-001", title: "Client Server Architecture", category: "HLD", topic: "Foundations", difficulty: "EASY", estimatedMinutes: 30, tags: ["concept"] },
  { id: "hld-002", title: "HTTP & REST Basics", category: "HLD", topic: "Foundations", difficulty: "EASY", estimatedMinutes: 35, tags: ["concept"] },
  { id: "hld-003", title: "DNS", category: "HLD", topic: "Networking", difficulty: "EASY", estimatedMinutes: 25, tags: ["concept"] },
  { id: "hld-004", title: "CDN", category: "HLD", topic: "Networking", difficulty: "EASY", estimatedMinutes: 30, tags: ["concept"] },
  { id: "hld-005", title: "Load Balancer", category: "HLD", topic: "Scalability", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-006", title: "Caching Strategies", category: "HLD", topic: "Caching", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-007", title: "Redis Caching", category: "HLD", topic: "Caching", difficulty: "MEDIUM", estimatedMinutes: 45, tags: ["concept"], prerequisites: ["hld-006"] },
  { id: "hld-008", title: "Database Indexing", category: "HLD", topic: "Databases", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-009", title: "SQL vs NoSQL", category: "HLD", topic: "Databases", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept"] },
  { id: "hld-010", title: "Replication", category: "HLD", topic: "Databases", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-011", title: "Sharding & Partitioning", category: "HLD", topic: "Databases", difficulty: "HARD", estimatedMinutes: 50, tags: ["concept"], prerequisites: ["hld-010"] },
  { id: "hld-012", title: "Consistency Models", category: "HLD", topic: "Distributed Systems", difficulty: "HARD", estimatedMinutes: 45, tags: ["concept"] },
  { id: "hld-013", title: "CAP Theorem", category: "HLD", topic: "Distributed Systems", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept"] },
  { id: "hld-014", title: "Message Queues", category: "HLD", topic: "Messaging", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-015", title: "Kafka Essentials", category: "HLD", topic: "Messaging", difficulty: "HARD", estimatedMinutes: 50, tags: ["concept"], prerequisites: ["hld-014"] },
  { id: "hld-016", title: "Rate Limiting", category: "HLD", topic: "Reliability", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-017", title: "Object Storage", category: "HLD", topic: "Storage", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept"] },
  { id: "hld-018", title: "API Gateway", category: "HLD", topic: "Microservices", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept"] },
  { id: "hld-019", title: "Microservices Overview", category: "HLD", topic: "Microservices", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-020", title: "Event Driven Architecture", category: "HLD", topic: "Architecture", difficulty: "HARD", estimatedMinutes: 45, tags: ["concept"], prerequisites: ["hld-014"] },
  { id: "hld-021", title: "Observability", category: "HLD", topic: "Reliability", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-022", title: "Authentication", category: "HLD", topic: "Security", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"] },
  { id: "hld-023", title: "Authorization", category: "HLD", topic: "Security", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept"], prerequisites: ["hld-022"] },
  { id: "hld-024", title: "WebSockets", category: "HLD", topic: "Realtime", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept"] },
  { id: "hld-025", title: "Search Systems", category: "HLD", topic: "Search", difficulty: "HARD", estimatedMinutes: 45, tags: ["concept"] },

  // Practical designs
  {
    id: "hld-026",
    title: "Design URL Shortener",
    category: "HLD",
    topic: "System Design",
    difficulty: "MEDIUM",
    estimatedMinutes: 60,
    tags: ["practical"],
    prerequisites: ["hld-001", "hld-008"],
    problemStatement: "Design a URL shortening service with high read throughput and analytics.",
    expectedConcepts: ["Hashing", "Caching", "DB schema", "Redirect flow"],
  },
  {
    id: "hld-027",
    title: "Design WhatsApp",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["hld-024", "hld-014"],
    problemStatement: "Design a messaging system with delivery receipts, groups, and media.",
    expectedConcepts: ["WebSockets", "Queues", "Fanout", "Storage"],
  },
  {
    id: "hld-028",
    title: "Design YouTube",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["hld-004", "hld-017"],
    problemStatement: "Design video upload, processing, CDN delivery, and recommendations at a high level.",
    expectedConcepts: ["CDN", "Object storage", "Transcoding", "Feed"],
  },
  {
    id: "hld-029",
    title: "Design Netflix",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["hld-004", "hld-006"],
    problemStatement: "Design a streaming platform focusing on playback, catalog, and personalization.",
    expectedConcepts: ["CDN", "Caching", "Microservices"],
  },
  {
    id: "hld-030",
    title: "Design Twitter/X",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["hld-011", "hld-006"],
    problemStatement: "Design a timeline/news feed system with follows and fanout strategies.",
    expectedConcepts: ["Fanout", "Caching", "Sharding"],
  },
  {
    id: "hld-031",
    title: "Design Instagram",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 70,
    tags: ["practical"],
    prerequisites: ["hld-017", "hld-006"],
    problemStatement: "Design photo sharing with feeds, stories, and media storage.",
    expectedConcepts: ["Object storage", "CDN", "Feed generation"],
  },
  {
    id: "hld-032",
    title: "Design Uber",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 80,
    tags: ["practical"],
    prerequisites: ["hld-016", "hld-014"],
    problemStatement: "Design ride matching, location updates, and dispatch at scale.",
    expectedConcepts: ["Geo indexing", "Matching", "Realtime"],
  },
  {
    id: "hld-033",
    title: "Design Food Delivery HLD",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 70,
    tags: ["practical"],
    prerequisites: ["hld-019", "hld-014"],
    problemStatement: "Design order placement, restaurant discovery, and delivery tracking.",
    expectedConcepts: ["Microservices", "Queues", "Maps"],
  },
  {
    id: "hld-034",
    title: "Design Notification System",
    category: "HLD",
    topic: "System Design",
    difficulty: "MEDIUM",
    estimatedMinutes: 60,
    tags: ["practical"],
    prerequisites: ["hld-014", "hld-016"],
    problemStatement: "Design a multi-channel notification platform with retries and preferences.",
    expectedConcepts: ["Queues", "Rate limiting", "Templates"],
  },
  {
    id: "hld-035",
    title: "Design Chat System",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 70,
    tags: ["practical"],
    prerequisites: ["hld-024", "hld-010"],
    problemStatement: "Design 1:1 and group chat with online presence and message history.",
    expectedConcepts: ["WebSockets", "Replication", "Storage"],
  },
  {
    id: "hld-036",
    title: "Design File Storage",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 70,
    tags: ["practical"],
    prerequisites: ["hld-017", "hld-010"],
    problemStatement: "Design a Dropbox-like file storage with sync and versioning.",
    expectedConcepts: ["Chunking", "Dedup", "Metadata DB"],
  },
  {
    id: "hld-037",
    title: "Design Rate Limiter",
    category: "HLD",
    topic: "System Design",
    difficulty: "MEDIUM",
    estimatedMinutes: 55,
    tags: ["practical"],
    prerequisites: ["hld-016", "hld-007"],
    problemStatement: "Design a distributed rate limiter (token bucket / sliding window).",
    expectedConcepts: ["Redis", "Algorithms", "Consistency"],
  },
  {
    id: "hld-038",
    title: "Design News Feed",
    category: "HLD",
    topic: "System Design",
    difficulty: "HARD",
    estimatedMinutes: 70,
    tags: ["practical"],
    prerequisites: ["hld-006", "hld-011"],
    problemStatement: "Design a personalized news feed with ranking and caching.",
    expectedConcepts: ["Fanout", "Ranking", "Caching"],
  },
];

export const revisionContent: SeedContent[] = [
  { id: "rev-001", title: "DSA Quick Revision Session", category: "REVISION", topic: "Revision", difficulty: "EASY", estimatedMinutes: 20, tags: ["revision"], isRevision: true },
  { id: "rev-002", title: "Pattern Flashcards", category: "REVISION", topic: "Revision", difficulty: "EASY", estimatedMinutes: 20, tags: ["revision"], isRevision: true },
  { id: "rev-003", title: "Weak Topic Drill", category: "REVISION", topic: "Revision", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["revision"], isRevision: true },
  { id: "rev-004", title: "LLD Pattern Refresh", category: "REVISION", topic: "Revision", difficulty: "EASY", estimatedMinutes: 25, tags: ["revision"], isRevision: true },
  { id: "rev-005", title: "HLD Concept Flash Review", category: "REVISION", topic: "Revision", difficulty: "EASY", estimatedMinutes: 25, tags: ["revision"], isRevision: true },
];

export const mockContent: SeedContent[] = [
  { id: "mock-001", title: "Timed DSA Mock (Easy/Medium)", category: "MOCK", topic: "Mock Interview", difficulty: "MEDIUM", estimatedMinutes: 60, tags: ["mock"] },
  { id: "mock-002", title: "Timed DSA Mock (Medium/Hard)", category: "MOCK", topic: "Mock Interview", difficulty: "HARD", estimatedMinutes: 75, tags: ["mock"] },
  { id: "mock-003", title: "LLD Mock Interview", category: "MOCK", topic: "Mock Interview", difficulty: "HARD", estimatedMinutes: 60, tags: ["mock"] },
  { id: "mock-004", title: "HLD Mock Interview", category: "MOCK", topic: "Mock Interview", difficulty: "HARD", estimatedMinutes: 60, tags: ["mock"] },
  { id: "mock-005", title: "Full Loop Simulation", category: "MOCK", topic: "Mock Interview", difficulty: "HARD", estimatedMinutes: 90, tags: ["mock"] },
];
