import type { SeedContent } from "./dsa";

export const lldContent: SeedContent[] = [
  // Concepts
  { id: "lld-001", title: "OOP Fundamentals", category: "LLD", topic: "OOP", difficulty: "EASY", estimatedMinutes: 30, tags: ["concept"], skills: ["oop"], description: "Objects, classes, encapsulation, abstraction, inheritance, polymorphism." },
  { id: "lld-002", title: "SOLID Principles", category: "LLD", topic: "SOLID", difficulty: "MEDIUM", estimatedMinutes: 40, tags: ["concept"], skills: ["solid"], prerequisites: ["lld-001"] },
  { id: "lld-003", title: "Composition vs Inheritance", category: "LLD", topic: "OOP", difficulty: "EASY", estimatedMinutes: 25, tags: ["concept"], prerequisites: ["lld-001"] },
  { id: "lld-004", title: "Interfaces & Contracts", category: "LLD", topic: "OOP", difficulty: "EASY", estimatedMinutes: 25, tags: ["concept"], prerequisites: ["lld-001"] },
  { id: "lld-005", title: "Dependency Injection", category: "LLD", topic: "SOLID", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["concept"], prerequisites: ["lld-002"] },
  { id: "lld-006", title: "UML & Class Diagrams", category: "LLD", topic: "UML", difficulty: "EASY", estimatedMinutes: 30, tags: ["concept"] },
  { id: "lld-007", title: "Factory Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept", "pattern"], prerequisites: ["lld-001"] },
  { id: "lld-008", title: "Abstract Factory Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 35, tags: ["concept", "pattern"], prerequisites: ["lld-007"] },
  { id: "lld-009", title: "Builder Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["concept", "pattern"] },
  { id: "lld-010", title: "Strategy Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["concept", "pattern"] },
  { id: "lld-011", title: "Observer Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["concept", "pattern"] },
  { id: "lld-012", title: "Decorator Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["concept", "pattern"] },
  { id: "lld-013", title: "Adapter Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 25, tags: ["concept", "pattern"] },
  { id: "lld-014", title: "Singleton Pattern", category: "LLD", topic: "Design Patterns", difficulty: "EASY", estimatedMinutes: 25, tags: ["concept", "pattern"] },
  { id: "lld-015", title: "State Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["concept", "pattern"] },
  { id: "lld-016", title: "Command Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 30, tags: ["concept", "pattern"] },
  { id: "lld-017", title: "Template Method Pattern", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 25, tags: ["concept", "pattern"] },
  { id: "lld-018", title: "Factory + Strategy Combined", category: "LLD", topic: "Design Patterns", difficulty: "MEDIUM", estimatedMinutes: 45, tags: ["concept", "pattern"], prerequisites: ["lld-007", "lld-010"] },

  // Practical
  {
    id: "lld-019",
    title: "Parking Lot System",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "MEDIUM",
    estimatedMinutes: 60,
    tags: ["practical"],
    prerequisites: ["lld-001", "lld-002"],
    problemStatement: "Design a parking lot that supports multiple floors, vehicle types, ticketing, and fee calculation.",
    expectedConcepts: ["OOP", "Strategy", "Factory", "Enums"],
  },
  {
    id: "lld-020",
    title: "Splitwise / Expense Sharing",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["lld-002", "lld-010"],
    problemStatement: "Design an expense-sharing app that supports equal, exact, and percentage splits with balances.",
    expectedConcepts: ["Strategy", "SOLID", "Graph balances"],
  },
  {
    id: "lld-021",
    title: "Tic Tac Toe",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "EASY",
    estimatedMinutes: 45,
    tags: ["practical"],
    prerequisites: ["lld-001"],
    problemStatement: "Design a tic-tac-toe game with board, players, win detection, and extensible board size.",
    expectedConcepts: ["OOP", "State"],
  },
  {
    id: "lld-022",
    title: "Elevator System",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["lld-015", "lld-010"],
    problemStatement: "Design an elevator controller for multiple elevators with request scheduling.",
    expectedConcepts: ["State", "Strategy", "Concurrency basics"],
  },
  {
    id: "lld-023",
    title: "ATM Machine",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "MEDIUM",
    estimatedMinutes: 60,
    tags: ["practical"],
    prerequisites: ["lld-015", "lld-002"],
    problemStatement: "Design an ATM supporting authenticate, withdraw, deposit, and balance inquiry flows.",
    expectedConcepts: ["State Machine", "SOLID"],
  },
  {
    id: "lld-024",
    title: "Library Management System",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "MEDIUM",
    estimatedMinutes: 60,
    tags: ["practical"],
    prerequisites: ["lld-001", "lld-006"],
    problemStatement: "Design catalog, borrow/return, membership, and fine calculation for a library.",
    expectedConcepts: ["OOP", "CRUD design"],
  },
  {
    id: "lld-025",
    title: "Car Rental System",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "MEDIUM",
    estimatedMinutes: 60,
    tags: ["practical"],
    prerequisites: ["lld-002", "lld-010"],
    problemStatement: "Design vehicle inventory, reservations, pricing strategies, and payment.",
    expectedConcepts: ["Strategy", "Factory"],
  },
  {
    id: "lld-026",
    title: "Movie Ticket Booking",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["lld-002", "lld-014"],
    problemStatement: "Design showtimes, seat locking, booking, and payment for a cinema.",
    expectedConcepts: ["Concurrency", "Locking", "State"],
  },
  {
    id: "lld-027",
    title: "Food Delivery LLD",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["lld-011", "lld-010"],
    problemStatement: "Design order lifecycle, restaurant catalog, delivery assignment, and notifications.",
    expectedConcepts: ["Observer", "State", "Strategy"],
  },
  {
    id: "lld-028",
    title: "Ride Sharing LLD",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "HARD",
    estimatedMinutes: 75,
    tags: ["practical"],
    prerequisites: ["lld-010", "lld-011"],
    problemStatement: "Design rider/driver matching, trip lifecycle, and fare calculation.",
    expectedConcepts: ["Strategy", "Observer", "Matching"],
  },
  {
    id: "lld-029",
    title: "Vending Machine",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "MEDIUM",
    estimatedMinutes: 50,
    tags: ["practical"],
    prerequisites: ["lld-015"],
    problemStatement: "Design a vending machine with inventory, payment, and dispense states.",
    expectedConcepts: ["State Pattern"],
  },
  {
    id: "lld-030",
    title: "Chess Game",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "HARD",
    estimatedMinutes: 80,
    tags: ["practical"],
    prerequisites: ["lld-001", "lld-010"],
    problemStatement: "Design chess pieces, board, move validation, and game rules.",
    expectedConcepts: ["Inheritance vs composition", "Strategy"],
  },
  {
    id: "lld-031",
    title: "Logger Framework",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "MEDIUM",
    estimatedMinutes: 45,
    tags: ["practical"],
    prerequisites: ["lld-012", "lld-016"],
    problemStatement: "Design a configurable logger with levels, sinks, and formatting.",
    expectedConcepts: ["Chain of Responsibility", "Singleton careful usage"],
  },
  {
    id: "lld-032",
    title: "Notification System LLD",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "MEDIUM",
    estimatedMinutes: 55,
    tags: ["practical"],
    prerequisites: ["lld-011", "lld-007"],
    problemStatement: "Design multi-channel notifications (email, SMS, push) with templates.",
    expectedConcepts: ["Observer", "Factory", "Strategy"],
  },
  {
    id: "lld-033",
    title: "Payment System LLD",
    category: "LLD",
    topic: "System Design LLD",
    difficulty: "HARD",
    estimatedMinutes: 70,
    tags: ["practical"],
    prerequisites: ["lld-010", "lld-002"],
    problemStatement: "Design payment methods, refunds, idempotency, and transaction states.",
    expectedConcepts: ["Strategy", "State", "Idempotency"],
  },
];
